DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  `id`         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uuid`       VARCHAR(64) NOT NULL UNIQUE,
  `fname`      VARCHAR(255),
  `lname`      VARCHAR(255),
  `email`      VARCHAR(255) NOT NULL UNIQUE,
  `password`   VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE sessions (
  `id`         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uuid`       VARCHAR(64) NOT NULL UNIQUE,
  `fname`      VARCHAR(255),
  `lname`      VARCHAR(255),
  `email`      VARCHAR(255) NOT NULL,
  `usr_id`     INT,
  `created_at` TIMESTAMP NOT NULL,
  CONSTRAINT fk_session_user FOREIGN KEY (`usr_id`) REFERENCES users(`id`)
  ON UPDATE CASCADE 
  ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE posts (
  `id`         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uuid`       VARCHAR(64) NOT NULL UNIQUE,
  `body`       TEXT,
  `usr_id`     INT,
  `created_at` TIMESTAMP NOT NULL,
  CONSTRAINT fk_post_user FOREIGN KEY (`usr_id`) REFERENCES users(`id`)
  ON UPDATE CASCADE 
  ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;